### ISSUE TITLE
ATOM: Not all results returned, only last page?

### ISSUE THREAD

**Issue by jensb89** [hodgerpodger/staketaxcsv#16]
For ATOM it seems that only the latest page is returned.
For my address, it has 2 pages (shown on stake.tax) but the export is not showing the first transactions. Thus it might be that only the latest page is returned?

Either way something is missing. I have << 1000 txs, so it is not the size of txs.

I didn't have time yet to install gaia to try locally.

**Comment by hodgerpodger** [comment]
Hmm, not sure what's going on.  That's pretty odd, especially if stake.tax doesn't match CLI.  

Some random notes in case helpful:
  * If default.csv has transactions but something like koinly.csv has "missing" transactions, that's a different issue related to how tx_type=_* (i.e. _UNKNOWN) do not show up in koinly.csv .
  * If you have gaia in docker, that's only setup I have too for ATOM.  So you're good there.  
  * I don't think this is issue, but it's probably good to note that older "cosmoshub-3" transactions are not supported.  This doesn't really jive with your case since it appears on stake.tax.
  
If you'd like, DM/email the bookmark url (from website).  I can take a look and test myself to try and figure out what's going on.

**Comment by jensb89** [comment]
No I meant stake.tax is also missing the transactions, sry for the confusion. I may have not been clear enough on that. I meant I had no time yet to try the code locally (but I have checked it out already and set up a new python venv ;))
Adding the gaia version info might still be of interest 👍 

Then it is probably the fact that that these were cosmoshub-3 transactions, I didn't know those are not supported. Fortunately, I don't have too many cosmoshub-3 txs, I guess I will just fill them in manually then.

Thanks for your quick reply :)
Keep up the good work, it's a helpful tool! 👍

**Comment by hodgerpodger** [comment]
Ah, nice.   Glad at least the issue is known.  Sounds like I should add note to website for ATOM users.
