### ISSUE TITLE
More cosmos chains

### ISSUE THREAD

**Issue by mbolesta** [hodgerpodger/staketaxcsv#214]
I've got AssetMantle and Teritori in a fork. Is this something you'd want contributed back to main? I've got them tagged and can make separate pull requests.

Also planning on adding Sifchain, Rebus and Secret too. Just basic staking transaction support initially (in particular REStake MsExec ones).

I've just been using the [cosmos chain registry](https://github.com/cosmos/chain-registry) for public rest nodes to test with, not sure if there's a better way... I'm new to blockchain dev.

Let me know.

**Comment by hodgerpodger** [comment]
Please do!  

I'll likely merge quickly but more gradually add it chain-by-chain to the stake.tax website, since I will establish some basic internal testing for each.

Yup, for many cosmos chains, there's not many options in terms of nodes.  The cosmos chain registry is my starting point as well (I'm not exactly a blockchain dev myself either).

**Comment by mbolesta** [comment]
I usually try a few diff endpoints to see which returns the most data. Not sure how you do it on the website. Like do you need to run a full node or something to get all the history? I enabled REStake on some of these chains and am just trying to collect the transactions for my taxes...

**Comment by hodgerpodger** [comment]
Nah, no full nodes.  I do exactly what you did, in terms of trial-and-error different endpoints to see which returns the most history.

Unfortunately, same limitations apply to stake.tax.

**Comment by mbolesta** [comment]
Alright I'll open up some PRs then and close this issue
