### ISSUE TITLE
Internal error when running Luna 1 generation 

### ISSUE THREAD

**Issue by goriunov** [hodgerpodger/staketaxcsv#276]
Looks like Luna1 tax generation is broken, as the generation process is failing with internal server error:

![image](https://user-images.githubusercontent.com/18750503/229319906-885e5a80-81ec-4fde-99b4-1e2f88132557.png)

**Comment by jrstrunk** [comment]
Seems like this is because columbus-fcd.terra.dev is down. I am emailing AllNodes about it to see if they can bring it back up. In the meantime I am looking into a workaround locally.

**Comment by jrstrunk** [comment]
This can be fixed by replacing the string literal assigned to `FCD_URL` on line 9 of `src/staketaxcsv/luna1/api_fcd.py` with "https://terra-classic-fcd.publicnode.com". This new url can be found on Public Node's website here: https://columbus-lcd.terra.dev/. I am not sure if the maintainers want to replace the old URL or wait for Public Node to bring it back up.

**Comment by hodgerpodger** [comment]
No issues over last few days.  Closing
