### ISSUE TITLE
report_kuji: invalid URL. No scheme supplied

### ISSUE THREAD

**Issue by digidoc2** [hodgerpodger/staketaxcsv#293]
Hello,

Thank you very much for your staketax tool!

After following all installation instructions, I can successfully execute
python staketaxcsv/report_juno.py #JUNO_ADDRESS#
, but for KUJI, I get the following error message (see below).

Can you tell me what I may be doing wrong?

Thank you very much,
Best,
Ron

------
(base) $ python3 staketaxcsv/report_kuji.py #KUJI_ADDRESS#
INFO:root:localconfig: {'__module__': 'staketaxcsv.kuji.config_kuji', 'ibc_addresses': {}, 'contract_history': {}, '__doc__': 
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '/cosmos/tx/v1beta1/txs': No scheme supplied. Perhaps you meant http:///cosmos/tx/v1beta1/txs?
(

**Comment by hodgerpodger** [comment]
Ah, try:

```
export STAKETAX_KUJI_NODE=<some_lcd_url_>
```

Ah yeah, I probably should provide better error message or clues since lots of folks run into this.  For some like KUJI, you need to supply the environment variable like above.
   * Sample list of kuji lcd urls: https://github.com/hodgerpodger/staketaxcsv/blob/main/src/staketaxcsv/cosmosplus/list_lcd.json
   * The environment variables that need to be filled in for certain reports can be found at `sample.env`.  I did not want to use some nodes as defaults for various reasons.

**Comment by digidoc2** [comment]
Thank you very much, hodgerpodger!
