### ISSUE TITLE
Unable to fetch txid, Probably old transaction where api fails. 

### ISSUE THREAD

**Issue by N11cK** [hodgerpodger/staketaxcsv#348]
When running below function I always run into the error message as stated in the title. Am I doing something wrong?
`staketaxcsv.csv(ticker="SOL", wallet_address=wallet_address, csv_format="default", path="/var/WalletAnalyzer/tmp/test2.csv", options=None, logs=True)`

Example errors with txids:
WARNING:root:Unable to fetch txid=5EMcTYcT7aTggDhuPBnuT89rhNutcL4A5hgJ7wKnvZ45hncXSjgt3RWSQhatYdRbx6Kg3Reupba174m85nVKmRu.  Probably old transaction where api fails.
WARNING:root:Unable to fetch txid=3MNVVD3LfmciXRae6RKSdvaLVKWWsruG987yLR41HhNGzijx5NG82bsjVVDoP3i3xBviX9JD782ubbjfkrkPPJPv.  Probably old transaction where api fails.
WARNING:root:Unable to fetch txid=4zRMBBtxbrLDUQwL5UiE5RVo1SbNAZsj77UST3aXnsWUeTYECrKu7E2SYdtG7umfB5L5J7DbaYy7m8bLWRGUZzij.  Probably old transaction where api fails.
WARNING:root:Unable to fetch txid=4PohPMVXY1FARnrkveNiA26vaG29UhsA4TkSDnjHdWLg915BzHt6bLrn5hAUguCWMigzvvS3Pp4DrpXPnoai4wDG.  Probably old transaction where api fails.

**Comment by hodgerpodger** [comment]
It works for me, but I'm guessing you're doing anything wrong.  I'm guessing right now the solana api/rpc call for getting transaction data is failing intermittently (http 200 response with empty result), and the code does not handle gracefully by detecting and retrying.  This is probably newer behavior due to congestion--so it's probably a bug I need to fix.

Note: I use a quicknode private solana rpc provider, such that it doesn't run into this issue, as opposed to mainnet beta.

This is guesswork.  Does the error message occur on different txid's each run, as opposed to identical txids?

**Comment by N11cK** [comment]
It keeps happening on the same txid's and I've had the same issue for a couple days across different wallets.
Can I use a different solana endpoint that wouldn't fail these? is a quicknode private solana rpc provider paid? any free options?
thank you

**Comment by hodgerpodger** [comment]
I tested it with mainnet beta and am getting same issues you are facing.  Looks like I'll need to rework to handle its throttling.  But yeah quicknode private solana rpc is a good option I think.  It's generally paid but I just checked and looks like it has very ample free amount of credits (50 million per month).  

Just signup for a solana node endpoint on quicknode and set:

`export STAKETAX_SOL_NODE=https://<somename>.solana-mainnet.quiknode.pro/<somekey>/` to your quicknode endpoint.

That should be it.
