### ISSUE TITLE
Caching all transactions, 

### ISSUE THREAD

**Issue by fentas** [hodgerpodger/staketaxcsv#48]
For my personal setup also to debug my transactions I implemented a second Cache class which stores all information within a MongoDB.
Information as in transactions responses, and contract call responses.

At first I implemented them in dynamoDB but as it is limited to 400kb for each data set this is impossible to do.

For me, this has the benefit right now that it will only fetch 10 transactions and if any of them already exists it will fetch the rest from mongo.

Not sure if you want this in this repo. If you do I would need to clean this up most likely and it is only implemented for terra right now but should be usable over all chains.

**Comment by hodgerpodger** [comment]
Nice.

Yeah a mongodb cache class (or however it fits) would be nice as an example for alternative cache, even if only for debugging.  I presume locally, mongodb is run with docker?

I'm not very thrilled with my own cache class methods.

I'd say I'd be happy to include, with the caveat that it's only used with some flag turned on(like csv option or environment variable), since I'm not keen on maintaining mongodb in production.
